{
 "title": "WireGuard Exporter",
 "tags": [
  "wireguard",
  "vpn",
  "networking"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(wireguard_interface_up, instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(wireguard_interface_up{instance=~\"$instance\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_interface_up{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_interface_peers{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Listen Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_interface_listen_port{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Time Since Last Handshake",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - wireguard_peer_latest_handshake_seconds{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(wireguard_peer_receive_bytes_total{interface=~\"$interface\"}[5m])",
     "legendFormat": "{{public_key}} received"
    },
    {
     "expr": "irate(wireguard_peer_transmit_bytes_total{interface=~\"$interface\"}[5m])",
     "legendFormat": "{{public_key}} sent"
    }
   ]
  },
  {
   "title": "Peer Traffic Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "wireguard_peer_receive_bytes_total{interface=~\"$interface\"}",
     "legendFormat": "{{public_key}} received"
    },
    {
     "expr": "wireguard_peer_transmit_bytes_total{interface=~\"$interface\"}",
     "legendFormat": "{{public_key}} sent"
    }
   ]
  },
  {
   "title": "Peer Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "wireguard_peer_latest_handshake_seconds{instance=~\"$instance\", interface=~\"$interface\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_peer_receive_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_peer_transmit_bytes_total{instance=~\"$instance\", interface=~\"$interface\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}